project_id = "zsyzkwamxqitamiljyer"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.admin-subscribers]
verify_jwt = false

[functions.serve-image]
verify_jwt = false

[functions.r]
verify_jwt = false

[functions.validate-signup]
verify_jwt = false
